name: Release

on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'

jobs:

  build-and-publish-public:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: galleoncore/powdermonkey
          tags: |
          type=semver,pattern={{version}}
          type=semver,pattern=lts-alpine-{{version}}

      - name: Substitute variables
        uses: microsoft/variable-substitution@v1 
        with:
          files: 'src/configuration/appsettings.json'
        env:
          CONSOLE_LOGGING.ENABLED: true
          FILE_LOGGING.ENABLED: false
          AZURE_LOGGING.ENABLED: false

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  build-and-publish-logging-enabled:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: galleoncore/powdermonkey
          tags: |
          type=semver,pattern=logging-{{version}}

      - name: Substitute variables
        uses: microsoft/variable-substitution@v1 
        with:
          files: 'src/configuration/appsettings.json'
        env:
          CONSOLE_LOGGING.ENABLED: true
          FILE_LOGGING.ENABLED: false
          AZURE_LOGGING.ENABLED: true
          AZURE_LOGGING.MONITORING_URL: ${{ secrets.AZURE_MONITORING_URL}}

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}