name: Release

on:
  push:
    tags:
      - 'v*'

jobs:

 build-and-publish-public:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Node
        uses: actions/setup-node@v1

      - name: Install powdermonkey Dependencies
        run: npm install -D ./powdermonkey
      - name: Run Powdermonkey tests
        run: mocha --reporter spec ./powdermonkey
        
      - name: Install Pricebot Dependencies 
        run: npm install -D ./pricebots
      - name: Run Pricebot tests
        run: mocha --reporter spec ./pricebots

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: Extract metadata (tags, labels) for powdermonkey
        id: meta_powdermonkey
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: |
            galleoncore/powdermonkey
          flavor: |
            latest=true
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern=lts-alpine-{{version}}

      - name: Extract metadata (tags, labels) for pricebot
        id: meta_pricebot
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: |
            galleoncore/pricebot
          flavor: |
            latest=true
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern=lts-alpine-{{version}}

      - name: Substitute variables
        uses: microsoft/variable-substitution@v1 
        with:
          files: './powdermonkey/src/configuration/appsettings.json'
        env:
          CONSOLE_LOGGING.ENABLED: true
          FILE_LOGGING.ENABLED: false
          AZURE_LOGGING.ENABLED: false

      - name: Build and push powdermonkey image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: ./powdermonkey
          push: true
          tags: ${{ steps.meta_powdermonkey.outputs.tags }}
          labels: ${{ steps.meta_powdermonkey.outputs.labels }}

      - name: Build and push pricebots image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: ./pricebots
          push: true
          tags: ${{ steps.meta_pricebot.outputs.tags }}
          labels: ${{ steps.meta_pricebot.outputs.labels }}

 build-and-publish-production:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Node
        uses: actions/setup-node@v1

      - name: Install powdermonkey Dependencies
        run: npm install -D ./powdermonkey
      - name: Run Powdermonkey tests
        run: mocha --reporter spec ./powdermonkey

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: Extract metadata (tags, labels) for Docker - Logging Version
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: |
            galleoncore/powdermonkey
          flavor: |
            prefix=logging
          tags: |
            type=semver,pattern={{version}}

      - name: Substitute variables
        uses: microsoft/variable-substitution@v1 
        with:
          files: './powdermonkey/src/configuration/appsettings.json'
        env:
          CONSOLE_LOGGING.ENABLED: false
          FILE_LOGGING.ENABLED: false
          AZURE_LOGGING.ENABLED: true
          AZURE_LOGGING.MONITORING_URL: ${{ secrets.AZURE_MONITORING_URL}}

      - name: Build and push powdermonkey production image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: ./powdermonkey
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      
      - name: Print tags
        run: echo "Tags are ${{ steps.meta.outputs.tags }}"

      - name: Print labels
        run: echo "Labels are ${{ steps.meta.outputs.labels }}"